### PR TITLE
64-bit libmd5 is no longer required

### PR DESCRIPTION
**Pull request by hadfl**

### CODE REVIEW

**Comment by danmcd** [comment]
Is this because of https://www.illumos.org/issues/14671 ?

Make sure nothing in cmd uses it either.  A quick glance through illumos-joyent yields:

```
kebe(usr/src)[0]% git grep -l -- -lmd5 | grep Makefile
cmd/boot/installboot/Makefile.com
cmd/boot/installgrub/Makefile
cmd/ndmpd/Makefile
cmd/svc/mfstscan/Makefile
cmd/svc/startd/Makefile
cmd/svc/svccfg/Makefile
tools/btxld/Makefile
kebe(usr/src)[0]% 
```

**Comment by hadfl** [comment]
i think all the binaries that `kayak` ships that still use `libmd5` are the 32-bit which was not removed with this commit.

**Comment by danmcd** [comment]
Thank you.  (I do think we might wish to remove -lmd5 from cmd as well, but that isn't the issue here at all.)

**Review by danmcd — APPROVED** [review]
So it's clearL my comment earlier was addressed.

**Comment by citrus-it** [comment]
> So it's clearL my comment earlier was addressed.

The way we have kayak set up now, it fails to build if there are unused libraries (or missing libraries which are required), so the reason for this PR is:

```
***** BUILD ERROR ***** (system/install/kayak-kernel)
+Unused library lib/amd64/libmd5.so.1
```

**Review by citrus-it — APPROVED** [review]

**Pull request merged**
